<section>
    <h4>Le Dernier match</h4>
    <div>
        <h5><?=$data['lastMatch']['game']->getName()?></h5>
        <h6><?=$data['lastMatch']['game']->getDate()?></h6>
        <div class="matchs">
            <img src="<?=$data['lastMatch']['team_1']->getUrl()?>" alt="<?=$data['lastMatch']['team_1']->getUrl()?>">
            <img src="<?=$data['lastMatch']['team_2']->getUrl()?>" alt="<?=$data['lastMatch']['team_2']->getUrl()?>">
        </div>
        <p><?=$data['lastMatch']['winner']->getName()?></p>
    </div>
</section>