<section class="topTeam">
    <h4>La team à la une</h4>
    <div class="allTeam">
        <img src="<?=$data['team']->getUrl()?>" alt="<?=$data['team']->getAlt()?>">
        <div class="teamPlayers">
            <p><?=$data['team']->getName()?></p>
            <p>Les players</p>
            <div class="players">
                <?php foreach($data["players"] as $key => $player): ?>
                    <div class="player">
                        <img src="<?= $player->getUrl() ?>" alt="<?= $player->getAlt() ?>">
                        <p><?= $player->getNickname()  ?></p>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>
</section>